# Generated by Django 6.0.7 on 2026-07-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('report_type', models.CharField(default='general', max_length=50)),
                ('farmer_id', models.BigIntegerField(blank=True, null=True)),
                ('created_by_id', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
