# Generated by Django 6.0.6 on 2026-07-11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('eucheuma', 'Eucheuma'), ('spinosum', 'Spinosum'), ('cotoni', 'Cotoni')], default='eucheuma', max_length=50)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('demand_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Market Price',
                'verbose_name_plural': 'Market Prices',
            },
        ),
    ]
