# Generated by Django 6.0.6 on 2026-07-11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='farmer',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('trader', 'Trader'), ('admin', 'Admin')], default='farmer', max_length=20),
        ),
        migrations.AddField(
            model_name='farmer',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
