# Generated by Django 6.0.6 on 2026-07-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0002_farmer_role_created_at_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmer',
            options={'verbose_name': 'Farmer', 'verbose_name_plural': 'Farmers'},
        ),
        migrations.AlterField(
            model_name='farmer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
