# Generated by Django 6.0.6 on 2026-07-11 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0003_alter_farmer_options_alter_farmer_phone'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='farmer',
            managers=[
            ],
        ),
    ]
