# Generated by Django 6.0.6 on 2026-07-11 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0005_marketprices_alter_farmer_managers_inventory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reports',
            options={'verbose_name': 'Report', 'verbose_name_plural': 'Report'},
        ),
    ]
