# Generated by Django 6.0.6 on 2026-07-11 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0006_alter_reports_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'Inventory', 'verbose_name_plural': 'Inventory'},
        ),
    ]
