# Generated by Django 6.0.7 on 2026-07-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0007_alter_inventory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('trader', 'Trader')], default='farmer', max_length=20),
        ),
    ]
