# Generated by Django 6.0.7 on 2026-07-14 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0008_alter_farmer_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketprices',
            options={'verbose_name': 'Market Price', 'verbose_name_plural': 'Market Prices'},
        ),
        migrations.AlterModelOptions(
            name='production',
            options={'verbose_name': 'Production', 'verbose_name_plural': 'Production Records'},
        ),
        migrations.AlterModelOptions(
            name='reports',
            options={'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
    ]
