# Generated by Django manually - Usafi wa Microservices
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # Hapa tumeweka tupu ili isitegemee database nyingine yoyote!
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('production', 'Production Report'), ('inventory', 'Inventory Report'), ('sales', 'Sales Report'), ('financial', 'Financial Report')], max_length=20)),
                ('farmer_id', models.IntegerField(blank=True, help_text='ID ya Mkulima kutoka microservice ya Farmers', null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.CharField(blank=True, help_text='Njia ya faili la PDF au Excel lililozalishwa', max_length=255, null=True)),
                ('summary_data', models.TextField(blank=True, help_text='Data ya muhtasari katika mfumo wa JSON au Maandishi', null=True)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
        ),
    ]