# Generated by Django 6.0.7 on 2026-07-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeaweedProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_id', models.IntegerField(blank=True, help_text='ID ya Mkulima kutoka microservice ya Farmers', null=True)),
                ('date', models.DateField()),
                ('quantity', models.FloatField(default=0.0)),
                ('type', models.CharField(default='Unknown', max_length=50)),
            ],
        ),
    ]
