# Generated by Django 6.0.7 on 2026-07-14 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seaweedproduction',
            options={'verbose_name': 'Seaweed Production', 'verbose_name_plural': 'Seaweed Production'},
        ),
    ]
